#!/usr/bin/env bash
# Build ciPHer-bench-phagehostlearn-data.zip from the laptop.
# Output: /Users/leannmlindsey/Desktop/ciPHer-bench-data-zips/ciPHer-bench-phagehostlearn-data.zip
#
# Layout MIRRORS the laptop layout under data/ so that the wrappers'
# env vars (CIPHER_REPO, CIPHER_VAL_GENOMES, PHL_REPO) keep working
# unchanged — only the prefix changes.
#
# Contents (extracts to data/ on Delta):
#   data/PhageHostLearn/                      Upstream Boeckaerts clone +
#                                             trained XGB model + Zenodo unpacked
#   data/cipher/data/validation_data/
#       metadata/validation_rbps_all.faa
#       HOST_RANGE/<DS>/metadata/             interaction_matrix.tsv +
#                                             phage_protein_mapping.csv per DS
#   data/cipher_val_genomes/<DS>/kaptive_out/Locibase.json
#                                             (PBIP + UCSD only; others must
#                                              be generated by running Kaptive)
#   data/cipher_val_genomes/Wang/phage_protein_ts_prediction_and_esm_embedding.pkl
#                                             (117 MB; only needed by
#                                              run_wang_inference.py)
#
# Run from the laptop.
set -euo pipefail

SRC_PHL_REPO="/Users/leannmlindsey/WORK/CLAUDE_PHAGEHOSTLEARN/claude_copy/PhageHostLearn"
SRC_CIPHER="/Users/leannmlindsey/WORK/PHI_TSP/cipher"
SRC_VAL_GENOMES="/Users/leannmlindsey/WORK/cipher_data/validation_genomes"
OUT_DIR="/Users/leannmlindsey/Desktop/ciPHer-bench-data-zips"
STAGE_PARENT="$(mktemp -d -t phl-data-zip-XXXXXX)"
STAGE_DIR="${STAGE_PARENT}/data"
ZIP_PATH="${OUT_DIR}/ciPHer-bench-phagehostlearn-data.zip"

mkdir -p "${OUT_DIR}" "${STAGE_DIR}"

echo "[1/4] Upstream PhageHostLearn clone (~3 GB with Zenodo)"
mkdir -p "${STAGE_DIR}/PhageHostLearn"
rsync -a --exclude '.git' --exclude '__pycache__' \
      "${SRC_PHL_REPO}/" "${STAGE_DIR}/PhageHostLearn/"

echo "[2/4] cipher_metadata mirror — replicate cipher's data/validation_data/ tree"
mkdir -p "${STAGE_DIR}/cipher/data/validation_data/metadata"
cp "${SRC_CIPHER}/data/validation_data/metadata/validation_rbps_all.faa" \
   "${STAGE_DIR}/cipher/data/validation_data/metadata/"
mkdir -p "${STAGE_DIR}/cipher/data/validation_data/HOST_RANGE"
for ds in CHEN GORODNICHIV PBIP UCSD PhageHostLearn; do
    SRC="${SRC_CIPHER}/data/validation_data/HOST_RANGE/${ds}/metadata"
    if [ -d "${SRC}" ]; then
        DST="${STAGE_DIR}/cipher/data/validation_data/HOST_RANGE/${ds}/metadata"
        mkdir -p "${DST}"
        cp -R "${SRC}/." "${DST}/"
        echo "  cipher/.../${ds}/metadata: $(du -sh "${DST}" | cut -f1)"
    fi
done

echo "[3/4] cipher_val_genomes mirror — per-dataset Kaptive output"
mkdir -p "${STAGE_DIR}/cipher_val_genomes"
for ds in CHEN GORODNICHIV PBIP UCSD PhageHostLearn Beamud Ferriol Wang; do
    LOCI="${SRC_VAL_GENOMES}/${ds}/kaptive_out/Locibase.json"
    if [ -f "${LOCI}" ]; then
        DST="${STAGE_DIR}/cipher_val_genomes/${ds}/kaptive_out"
        mkdir -p "${DST}"
        cp "${LOCI}" "${DST}/"
        echo "  cipher_val_genomes/${ds}/kaptive_out/Locibase.json: $(du -sh "${LOCI}" | cut -f1)"
    else
        echo "  cipher_val_genomes/${ds}/kaptive_out/Locibase.json: MISSING — run Kaptive first"
    fi
done

# Wang pickle (for run_wang_inference.py)
WANG_PKL="${SRC_VAL_GENOMES}/Wang/phage_protein_ts_prediction_and_esm_embedding.pkl"
if [ -f "${WANG_PKL}" ]; then
    mkdir -p "${STAGE_DIR}/cipher_val_genomes/Wang"
    cp "${WANG_PKL}" "${STAGE_DIR}/cipher_val_genomes/Wang/"
    echo "  cipher_val_genomes/Wang/phage_protein_ts_prediction_and_esm_embedding.pkl: $(du -sh "${WANG_PKL}" | cut -f1)"
fi

echo "  staged total: $(du -sh "${STAGE_DIR}" | cut -f1)"

echo "[4/4] Zip (fast compression — several minutes)"
cd "${STAGE_PARENT}"
zip -qr -1 "${ZIP_PATH}" data
du -sh "${ZIP_PATH}"

rm -rf "${STAGE_PARENT}"

echo
echo "Done. Zip at: ${ZIP_PATH}"
